Pidev.Presentation/Controllers/DepenseController.cs
using Pidev.data;
using Presentation.Models;
using Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using iTextSharp.text.html.simpleparser;
using System.Net.Mail;

namespace Pidev.Presentation.Controllers
{
    public class DepenseController : Controller
    {
        IMissionService pp = null;
        IExpensesService expService = null;

        public DepenseController()
        {
            expService = new ExpensesService();
            pp = new MissionService();
        }

        // GET: Expense
        public ActionResult Index(string searchString)
        {
            var maliste = new List<exp>();
            IEnumerable<expenses> expDomain = expService.GetAll();
            if (!String.IsNullOrEmpty(searchString))
            {
                expDomain = expService.GetexpByType(searchString);
            }

            foreach (var dep in expDomain)
            {

                maliste.Add(new exp
                {
                    id_Exp = dep.id_Exp,
                    DateExpense = dep.DateExpense,
                    NatureDepense = (NatureVM)dep.NatureDepense,
                    nbNuitete = dep.nbNuitete,
                    moyTransport = (MoyeneVM)dep.moyTransport,
                    distance = dep.distance,
                    Justificatif = dep.Justificatif,
                    MontantTotal = dep.MontantTotal,
                    commentaire = dep.commentaire,
                    mm_id_mission = dep.mm_id_mission,
                    nbVue = dep.nbVue
                    //Frexp_id_frais = dep.Frexp_id_frais
                }) ;
            }
            return View(maliste);
        }


        [HttpPost]
        [ValidateInput(false)]
        public FileResult Export(string GridHtml)
        {
            using (MemoryStream stream = new System.IO.MemoryStream())
            {
                StringReader sr = new StringReader(GridHtml);
                Document pdfDoc = new Document(PageSize.A4, 10f, 10f, 100f, 0f);
                PdfWriter writer = PdfWriter.GetInstance(pdfDoc, stream);
                pdfDoc.Open();
                XMLWorkerHelper.GetInstance().ParseXHtml(writer, pdfDoc, sr);
                pdfDoc.Close();
                return File(stream.ToArray(), "application/pdf", "Grid.pdf");
            }
        }













        // GET: Expense/Details/5
        public ActionResult Details(int id)
        {
            var s = expService.GetById(id);
            s.nbVue = s.nbVue + 1;
            return View(s);
          
        }


        // GET: Expense/Create
        public ActionResult Create()
        {
            var missions = pp.GetMany().ToList();

            ViewBag.listmiss = new SelectList(missions, "libelle", "libelle");
            ViewBag.listmiss = missions;
            return View();
        }

        // POST: Expense/Create
        [HttpPost]
        public ActionResult Create(exp dep, HttpPostedFileBase file, int abc)
        {
            var missions = pp.GetMany().ToList();

            ViewBag.listmiss = new SelectList(missions, "libelle", "libelle");
            ViewBag.listmiss = missions;
            if (!ModelState.IsValid || file == null || file.ContentLength == 0)
            {
                RedirectToAction("Create");
            }
            var fileName = "";

            if (file.ContentLength > 0)
            {
                fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("/Content/Upload/"), file.FileName);
                file.SaveAs(path);
            }
            expenses d = new expenses()
            {
                DateExpense = dep.DateExpense,
                NatureDepense = (Nature)dep.NatureDepense,
                nbNuitete = dep.nbNuitete,
                moyTransport = (Moyene)dep.moyTransport,
                distance = dep.distance,
                Justificatif = file.FileName,
                MontantTotal = dep.MontantTotal,
                commentaire = dep.commentaire,
                mm_id_mission = abc

            };
            d.Justificatif = file.FileName;
            d.mm_id_mission = abc;
            expService.Add(d);
            expService.Commit();
            // expService.Dispose();   //  @Html.DropDownList("m_id_mission", (SelectList)ViewData["listmiss




          

            return RedirectToAction("Index");


        }


        public ActionResult Edit(int id)
        {

            // GET: Expense/Edit/5
            if (id == null)

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            expenses dep = expService.GetById(id);
            expenses p1 = new expenses()
            {
                DateExpense = dep.DateExpense,
                NatureDepense = (Nature)dep.NatureDepense,
                nbNuitete = dep.nbNuitete,
                moyTransport = (Moyene)dep.moyTransport,
                distance = dep.distance,
                Justificatif = dep.Justificatif,
                MontantTotal = dep.MontantTotal,
                commentaire = dep.commentaire,
                mm_id_mission = dep.mm_id_mission

            };

            if (dep == null)
                return HttpNotFound();
            expService.Update(dep);
            expService.Commit();
            return View(p1);
        }

        // POST: Comment/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, exp dep)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (id == null)
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    expenses p = expService.GetById(id);

                    dep = new exp()
                    {
                        DateExpense = dep.DateExpense,
                        NatureDepense = (NatureVM)dep.NatureDepense,
                        nbNuitete = dep.nbNuitete,
                        moyTransport = (MoyeneVM)dep.moyTransport,
                        distance = dep.distance,
                        // Justificatif = file.FileName,
                        MontantTotal = dep.MontantTotal,
                        commentaire = dep.commentaire,
                        mm_id_mission = dep.mm_id_mission

                    };


                    if (p == null)
                        return HttpNotFound();

                    Console.WriteLine("updaaaaaaaaaaaate");
                    expService.Update(p);
                    expService.Commit();
                    // Service.Dispose();
                    return RedirectToAction("Index");
                    // return RedirectToAction("Index");
                }
                // TODO: Add delete logic here
                return View(dep);

            }
            catch
            {
                return View();
            }
        }


        // GET: Expense/Delete/5
        public ActionResult Delete(int id)
        {

            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            expenses dep = expService.GetById(id);
            exp p = new exp()
            {
                DateExpense = dep.DateExpense,
                NatureDepense = (NatureVM)dep.NatureDepense,
                nbNuitete = dep.nbNuitete,
                moyTransport = (MoyeneVM)dep.moyTransport,
                distance = dep.distance,
                Justificatif = dep.Justificatif,
                MontantTotal = dep.MontantTotal,
                commentaire = dep.commentaire,
                mm_id_mission = dep.mm_id_mission

            };

            if (dep == null)
                return HttpNotFound();
            expService.Delete(dep);
            expService.Commit();
            return View(p);
        }



        // POST: Expense/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, exp evt)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    if (id == null)
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    expenses dep = expService.GetById(id);
                    evt = new exp()
                    {
                        DateExpense = dep.DateExpense,
                        NatureDepense = (NatureVM)dep.NatureDepense,
                        nbNuitete = dep.nbNuitete,
                        moyTransport = (MoyeneVM)dep.moyTransport,
                        distance = dep.distance,
                        Justificatif = dep.Justificatif,
                        MontantTotal = dep.MontantTotal,
                        commentaire = dep.commentaire,
                        mm_id_mission = dep.mm_id_mission

                    };
                    if (dep == null)
                        return HttpNotFound();
                    Console.WriteLine("Deleted");
                    expService.Delete(dep);
                    expService.Commit();
                    // Service.Dispose();
                    return RedirectToAction("Index");
                }
                // TODO: Add delete logic here
                return View(evt);

            }
            catch
            {
                return View();
            }
        }
    }
}

Pidev.Presentation/Controllers/FraisController.cs
using Pidev.data;
using Presentation.Models;
using Service;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace Pidev.Presentation.Controllers
{
    public class FraisController : Controller
    {
        IFFraiSer a = null;
        IExpensesService b = null;
        // GET: Frai
        public FraisController()
        {
            b = new ExpensesService();
            a = new FFraiSer();
        }
        public ActionResult Index(string searchString)
        {
            var maliste = new List<fraiVM>();
            IEnumerable<frais> fDomain = a.GetMany();
            if (!String.IsNullOrEmpty(searchString))
            {
                fDomain = a.GetFraiByLib(searchString);
            }
            foreach (var vv in fDomain)
            {
        
                maliste.Add(new fraiVM
                {
                    id_frais = vv.id_frais,
                    libelle = vv.libelle,
                    DTreat = (DateTime)vv.DTreat,
                    NetRemb = vv.NetRemb,
                    StatusFrais = vv.StatusFrais,
                    uneExp_id_Exp = vv.uneExp_id_Exp,
              
                }) ;
     
            }
            return View(maliste);
        }


        // GET: Frai/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Frai/Create
        public ActionResult Create()
        {
            var depenses = b.GetMany().ToList();
            ViewBag.listexp = new SelectList(depenses, "id_Exp", " id_Exp");
            ViewBag.listexp = depenses;
            return View();
        }

        // POST: Frai/Create
        [HttpPost]
        public ActionResult Create(frais vv, int abc)
        {
            var depenses = b.GetMany().ToList();

            ViewBag.listexp = new SelectList(depenses, "id_Exp", "id_Exp");
            ViewBag.listmiss = depenses;

             fraiVM d = new fraiVM()
            {
                id_frais = vv.id_frais,
                libelle=vv.libelle,
                DTreat = (DateTime)vv.DTreat,
                NetRemb = vv.NetRemb,
                StatusFrais = vv.StatusFrais,
          
 
                uneExp_id_Exp=vv.uneExp_id_Exp
            };
            
            vv.uneExp_id_Exp = abc;
            a.Add(vv);
            a.Commit();
            //Service.Dispose();   

            string subject = "reglement de frais";

            string body = "Votre frai a été réalisé" +
                "<br/><a href = '></a>";

            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = true,
                Credentials = new NetworkCredential("zeineb.salah@esprit.tn", "esprit2018"),
                Timeout = 20000
            };
            MailMessage p = new MailMessage("zeineb.salah@esprit.tn", "zeineb.salah@esprit.tn");

            p.Subject = subject;
            p.Body = body;
            p.IsBodyHtml = true;


            smtp.Send(p);


            return RedirectToAction("Index");


        }

        public ActionResult Edit(int id)
        {
            frais dep = a.GetById(id);
            frais x = new frais();
         x.libelle = dep.libelle;
           x.NetRemb = dep.NetRemb;
            x.StatusFrais = dep.StatusFrais;

            Debug.WriteLine(x);
            a.Update(dep);
            a.Commit();

            return View(dep);
}
        
            // GET: Frais/Edit/5
 /*           public ActionResult Edit(int id,frais dep)
        {
            try
            {
                frais clb = a.GetById(id);
                clb.libelle = dep.libelle;
                clb.NetRemb = dep.NetRemb;
                clb.StatusFrais = dep.StatusFrais;
                
                Debug.WriteLine(clb);
                a.Update(clb);
                a.Commit();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        */
        // GET: Frais/Delete/5
        public ActionResult Delete(int id)
        {
           if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
           frais p = a.GetById(id);
            
              fraiVM p1 = new fraiVM()
            {
              
                libelle = p.libelle,
                DTreat = (DateTime)p.DTreat,
                NetRemb = p.NetRemb,
                StatusFrais = p.StatusFrais,

                uneExp_id_Exp = p.uneExp_id_Exp
            };
            
            if (p == null)
                return HttpNotFound();
            a.Delete(p);
            a.Commit();

            return View(p1);
        }


        // POST: Frais/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, fraiVM vv)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (id == null)
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    frais p = a.GetById(id);
                vv= new fraiVM()
                    {
                     
                        libelle = p.libelle,
                        DTreat = (DateTime)p.DTreat,
                        NetRemb = p.NetRemb,
                        StatusFrais = p.StatusFrais,

                        uneExp_id_Exp = p.uneExp_id_Exp
                    };
                    

                    if (p == null)
                        return HttpNotFound();
                    Console.WriteLine("Deleted");
                    a.Delete(p);
                    a.Commit();
                    // Service.Dispose();
                    return RedirectToAction("Index");
                }
                // TODO: Add delete logic here
                return View(vv);

            }
            catch
            {
                return View();
            }
        }
    }
}

Pidev.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom d'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mon application ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Pidev.Presentation/Views/Shared/_template.cshtml
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>AdminLTE 3 | Starter</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/template/script")
    @Styles.Render("~/template/css")
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand bg-white navbar-light border-bottom">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="index3.html" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Contact</a>
                </li>
            </ul>

            <!-- SEARCH FORM -->
            <form class="form-inline ml-3">
                <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Messages Dropdown Menu -->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="fa fa-comments-o"></i>
                        <span class="badge badge-danger navbar-badge">3</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <div class="media">
                                <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        Brad Diesel
                                        <span class="float-right text-sm text-danger"><i class="fa fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">Call me whenever you can...</p>
                                    <p class="text-sm text-muted"><i class="fa fa-clock-o mr-1"></i> 4 Hours Ago</p>
                                </div>
                            </div>
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <div class="media">
                                <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        John Pierce
                                        <span class="float-right text-sm text-muted"><i class="fa fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">I got your message bro</p>
                                    <p class="text-sm text-muted"><i class="fa fa-clock-o mr-1"></i> 4 Hours Ago</p>
                                </div>
                            </div>
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <div class="media">
                                <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        Nora Silvester
                                        <span class="float-right text-sm text-warning"><i class="fa fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">The subject goes here</p>
                                    <p class="text-sm text-muted"><i class="fa fa-clock-o mr-1"></i> 4 Hours Ago</p>
                                </div>
                            </div>
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                    </div>
                </li>
                <!-- Notifications Dropdown Menu -->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell-o"></i>
                        <span class="badge badge-warning navbar-badge">15</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <span class="dropdown-header">15 Notifications</span>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fa fa-envelope mr-2"></i> 4 new messages
                            <span class="float-right text-muted text-sm">3 mins</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fa fa-users mr-2"></i> 8 friend requests
                            <span class="float-right text-muted text-sm">12 hours</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fa fa-file mr-2"></i> 3 new reports
                            <span class="float-right text-muted text-sm">2 days</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
                        <i class="fa fa-th-large"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
              
                <span class="brand-text font-weight-light">AdminLTE 3</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/Content/12.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Espace-Manager</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                             with font-awesome or any other icon font library -->
                        <li class="nav-item has-treeview menu-open">
                            <a href="#" class="nav-link active">
                                <i class="nav-icon fa fa-dashboard"></i>
                                <p>
                                   Gestion-frais
                                    <i class="right fa fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li>

                                    @Html.ActionLink("Missions", "Index", "Mission", new { area = "" }, new { @class = "nav-link" })


                                </li>
                                <li>
                                    @Html.ActionLink("Dépenses", "Index", "Depense", new { area = "" }, new { @class = "nav-link" })



                                </li>
                                <li>
                                    @Html.ActionLink("Gestion-Frais", "Index", "Frais", new { area = "" }, new { @class = "nav-link" })



                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fa fa-th"></i>
                                <p>
                                    Simple Link
                                    <span class="right badge badge-danger">New</span>
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>


        <div class="content-wrapper">

            @RenderBody()

        </div>


        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
            <div class="p-3">
                <h5>Title</h5>

            </div>
        </aside>
        <!-- /.control-sidebar -->


    </div>

    @RenderSection("scripts", required: false)
   

    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>